name: Build cimgui Libraries via cmake.yml

on: [workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/cmake.yml
    with:
      lib-name: cimgui
      repo: JunaMeinhold/cimgui
      repo-tag: docking_inter
      output-dir: native
      cmake-flags: -DIMGUI_WCHAR32=ON -DIMGUI_FREETYPE=ON
      use-vcpkg: true
      vcpkg-packages: freetype
      bin-name-linux: cimgui.so
      bin-name-linux-normalized: cimgui.so
      bin-name-windows: Release/cimgui.dll
      bin-name-windows-normalized: cimgui.dll
      bin-name-osx: cimgui.dylib
      bin-name-osx-normalized: cimgui.dylib
      bin-name-android: cimgui.so
      bin-name-android-normalized: cimgui.so
      android-api: 23
