name: Build cimgui and addons Libraries

on: [workflow_dispatch]

jobs:
  build-cimgui:
    uses: JunaMeinhold/cmake-actions/cmake.yml@v1.0
    with:
      lib-name: cimgui
      repo: JunaMeinhold/cimgui
      repo-tag: docking_inter
      output-dir: native
      cmake-flags: -DIMGUI_WCHAR32=ON -DIMGUI_FREETYPE=ON
      use-vcpkg: true
      vcpkg-packages: freetype
      bin-name-linux: cimgui.so
      bin-name-linux-normalized: cimgui.so
      bin-name-windows: Release/cimgui.dll
      bin-name-windows-normalized: cimgui.dll
      bin-name-osx: cimgui.dylib
      bin-name-osx-normalized: cimgui.dylib
      bin-name-android: cimgui.so
      bin-name-android-normalized: cimgui.so
      android-api: 23
      create-pr: false
  build-cimplot:
    uses: JunaMeinhold/cmake-actions/cmake.yml@v1.0
    with:
      lib-name: cimplot
      repo: JunaMeinhold/cimplot
      repo-tag: master
      output-dir: native
      cmake-flags: -DIMGUI_WCHAR32=ON -DIMGUI_FREETYPE=ON
      bin-name-linux: cimplot.so
      bin-name-linux-normalized: cimplot.so
      bin-name-windows: Release/cimplot.dll
      bin-name-windows-normalized: cimplot.dll
      bin-name-osx: cimplot.dylib
      bin-name-osx-normalized: cimplot.dylib
      bin-name-android: cimplot.so
      bin-name-android-normalized: cimplot.so
      android-api: 23
      pre-configure-steps: git clone --recursive https://github.com/JunaMeinhold/cimgui.git
      create-pr: false
  build-cimnodes:
    uses: JunaMeinhold/cmake-actions/cmake.yml@v1.0
    with:
      lib-name: cimnodes
      repo: JunaMeinhold/cimnodes
      repo-tag: master
      output-dir: native
      cmake-flags: -DIMGUI_WCHAR32=ON -DIMGUI_FREETYPE=ON
      bin-name-linux: cimnodes.so
      bin-name-linux-normalized: cimnodes.so
      bin-name-windows: Release/cimnodes.dll
      bin-name-windows-normalized: cimnodes.dll
      bin-name-osx: cimnodes.dylib
      bin-name-osx-normalized: cimnodes.dylib
      bin-name-android: cimnodes.so
      bin-name-android-normalized: cimnodes.so
      android-api: 23
      pre-configure-steps: git clone --recursive https://github.com/JunaMeinhold/cimgui.git
      create-pr: false
  build-cimguizmo:
    uses: JunaMeinhold/cmake-actions/cmake.yml@v1.0
    with:
      lib-name: cimguizmo
      repo: JunaMeinhold/cimguizmo
      repo-tag: master
      output-dir: native
      cmake-flags: -DIMGUI_WCHAR32=ON -DIMGUI_FREETYPE=ON
      bin-name-linux: cimguizmo.so
      bin-name-linux-normalized: cimguizmo.so
      bin-name-windows: Release/cimguizmo.dll
      bin-name-windows-normalized: cimguizmo.dll
      bin-name-osx: cimguizmo.dylib
      bin-name-osx-normalized: cimguizmo.dylib
      bin-name-android: cimguizmo.so
      bin-name-android-normalized: cimguizmo.so
      android-api: 23
      pre-configure-steps: git clone --recursive https://github.com/JunaMeinhold/cimgui.git
      create-pr: false
  create-pr:
    uses: JunaMeinhold/cmake-actions/create-pr.yml@v1.0
    needs: [build-cimgui, build-cimplot, build-cimnodes, build-cimguizmo]
    with:
      lib-name: Dear ImGui + Addons
      repo-tag: latest
      output-dir: native
      branch: native-artifacts-branch
      base: master
      reviewers: JunaMeinhold
